---
- name: condition of playbook example
  hosts: all
  become: yes
  tasks:
    - name: install nginx in debian
      update_cache: yes
      command: apt install nginx -y
      when: ansible_os_family == "debian"
...