---
- name: condition of playbook example
  hosts: all
  become: yes
  tasks:
    - name: install nginx in debian
       commands: sudo apt install nginx -y
       when: ansible_os_family == "debian"
...