---
- name: example playbook for example
  hosts: all
  becomes: yes
      vars: 
        package: apache2
      tasks:
        name: installing package
        action: apt name="{{package}}" state=latest
... 