---
- name: write playbook for loop example
  hosts: all
  become: yes
  tasks: 
    - name: create multiplke user
      user: 
        name: "{{item}}" 
        state: present 
      with_items:
                 - yash
                 - sam
                 - ram
...