- name: installing nginx
  package:
    name: nginx
    state: latest
- name: coping index.html
  copy:
    srv: index.html
    dest: /var/www/html/
  notify:
    - startingnginx
- name: print msg
  debug: 
    msg: "{{URL}}"